### ISSUE TITLE
Publish to NPM as ES5

### ISSUE THREAD

**Issue by avindra** [elazzabi/longest-common-subsequence#1]
Please see:

https://github.com/elazzabi/fuzzy-string-matching/issues/1

**Comment by elazzabi** [comment]
Npm module updated to 1.0.3. Should be working now. Can you test if the issue is remaining?

**Comment by avindra** [comment]
This is also working ok now. Thank you :smile:

**Comment by elazzabi** [comment]
You are welcome man :smile:
